const SESSION_HISTORY = {
  STARTTIME: "startTime",
  DATE: "date",
  DURATION: "duration",
  NODE_USED: "node",
  DATA_CONSUMED: "dataConsumed",
  LOCATION_OF_NODE: "location",
};

const SESSION_HISTORY_COLUMNS = {
  [SESSION_HISTORY.STARTTIME]: "Session start time",
  [SESSION_HISTORY.DATE]: "Date",
  [SESSION_HISTORY.DURATION]: "Duration",
  [SESSION_HISTORY.NODE_USED]: "Node Used",
  [SESSION_HISTORY.DATA_CONSUMED]: "Data Consumed",
  [SESSION_HISTORY.LOCATION_OF_NODE]: "Location of Node",
} as const;

const SESSION_HISTORY_COLUMN_ORDER = [
  SESSION_HISTORY_COLUMNS.STARTTIME,
  SESSION_HISTORY_COLUMNS.DATE,
  SESSION_HISTORY_COLUMNS.DURATION,
  SESSION_HISTORY_COLUMNS.NODE_USED,
  SESSION_HISTORY_COLUMNS.NODE_USED,
  SESSION_HISTORY_COLUMNS.DATA_CONSUMED,
  SESSION_HISTORY_COLUMNS.LOCATION_OF_NODE,
] as const;

const SESSION_AGGREGATION = {
  ACTIVE_SESSIONS: "Active Sessions",
  TOTAL_SESSIONS: "Total Sessions",
  HIGHEST_ACTIVE_SESSIONS: "Highest Active Sessions",
  LONGEST_SESSION: "Longest Session",
} as const;

const SESSION_INDICATOR_TYPE = {
  INC: "INC",
  DEC: "DEC",
} as const;

const SESSION_ACTIVITY_CHART_TYPE = {
  DAY: "1D",
  MONTH: "1M",
  YEAR: "1Y",
} as const;

const SESSION_ACTIVITY_CHART_VIEW = [
  SESSION_ACTIVITY_CHART_TYPE.DAY,
  SESSION_ACTIVITY_CHART_TYPE.MONTH,
  SESSION_ACTIVITY_CHART_TYPE.YEAR,
] as const;

export {
  SESSION_HISTORY_COLUMNS,
  SESSION_HISTORY_COLUMN_ORDER,
  SESSION_AGGREGATION,
  SESSION_INDICATOR_TYPE,
  SESSION_ACTIVITY_CHART_TYPE,
  SESSION_ACTIVITY_CHART_VIEW,
  SESSION_HISTORY,
};
